# Generated by Django 5.2.12 on 2026-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='last_polled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='olt',
            name='olt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='olt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
