# Generated by Django 5.2.12 on 2026-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0002_olt_enabled_olt_last_polled_olt_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='onu_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onu',
            name='pon_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
